# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ICollector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ICollector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ICollector.proto\x12\tcollector\"/\n\x0bMeasurement\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t2G\n\nICollector\x12\x39\n\x0fSendMeasurement\x12\x16.collector.Measurement\x1a\x0e.collector.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ICollector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEASUREMENT']._serialized_start=31
  _globals['_MEASUREMENT']._serialized_end=78
  _globals['_ACK']._serialized_start=80
  _globals['_ACK']._serialized_end=101
  _globals['_ICOLLECTOR']._serialized_start=103
  _globals['_ICOLLECTOR']._serialized_end=174
# @@protoc_insertion_point(module_scope)
