# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitoraggio_latenze.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'monitoraggio_latenze.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amonitoraggio_latenze.proto\x12\x14monitoraggio_latenze\"\x17\n\x04Ping\x12\x0f\n\x07latency\x18\x01 \x01(\x03\"\x1d\n\tPingReply\x12\x10\n\x08pkt_rcvd\x18\x01 \x01(\x03\"\x07\n\x05\x45mpty\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb4\x01\n\x13MonitoraggioLatenze\x12L\n\x0bstream_ping\x12\x1a.monitoraggio_latenze.Ping\x1a\x1f.monitoraggio_latenze.PingReply(\x01\x12O\n\x12get_network_status\x12\x1b.monitoraggio_latenze.Empty\x1a\x1c.monitoraggio_latenze.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitoraggio_latenze_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PING']._serialized_start=52
  _globals['_PING']._serialized_end=75
  _globals['_PINGREPLY']._serialized_start=77
  _globals['_PINGREPLY']._serialized_end=106
  _globals['_EMPTY']._serialized_start=108
  _globals['_EMPTY']._serialized_end=115
  _globals['_STATUS']._serialized_start=117
  _globals['_STATUS']._serialized_end=141
  _globals['_MONITORAGGIOLATENZE']._serialized_start=144
  _globals['_MONITORAGGIOLATENZE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
