# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import monitoraggio_latenze_pb2 as monitoraggio__latenze__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in monitoraggio_latenze_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MonitoraggioLatenzeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.stream_ping = channel.stream_unary(
                '/monitoraggio_latenze.MonitoraggioLatenze/stream_ping',
                request_serializer=monitoraggio__latenze__pb2.Ping.SerializeToString,
                response_deserializer=monitoraggio__latenze__pb2.PingReply.FromString,
                _registered_method=True)
        self.get_network_status = channel.unary_unary(
                '/monitoraggio_latenze.MonitoraggioLatenze/get_network_status',
                request_serializer=monitoraggio__latenze__pb2.Empty.SerializeToString,
                response_deserializer=monitoraggio__latenze__pb2.Status.FromString,
                _registered_method=True)


class MonitoraggioLatenzeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def stream_ping(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_network_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitoraggioLatenzeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'stream_ping': grpc.stream_unary_rpc_method_handler(
                    servicer.stream_ping,
                    request_deserializer=monitoraggio__latenze__pb2.Ping.FromString,
                    response_serializer=monitoraggio__latenze__pb2.PingReply.SerializeToString,
            ),
            'get_network_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_network_status,
                    request_deserializer=monitoraggio__latenze__pb2.Empty.FromString,
                    response_serializer=monitoraggio__latenze__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitoraggio_latenze.MonitoraggioLatenze', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('monitoraggio_latenze.MonitoraggioLatenze', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonitoraggioLatenze(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def stream_ping(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/monitoraggio_latenze.MonitoraggioLatenze/stream_ping',
            monitoraggio__latenze__pb2.Ping.SerializeToString,
            monitoraggio__latenze__pb2.PingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_network_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitoraggio_latenze.MonitoraggioLatenze/get_network_status',
            monitoraggio__latenze__pb2.Empty.SerializeToString,
            monitoraggio__latenze__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
