// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: energyService.proto
// Protobuf Java Version: 4.31.1

package gRPC.EnergyService;

@com.google.protobuf.Generated
public final class EnergyServiceOuterClass {
  private EnergyServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      EnergyServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energy_service_Reading_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_energy_service_Reading_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energy_service_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_energy_service_Ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023energyService.proto\022\016energy_service\"(\n" +
      "\007Reading\022\020\n\010meter_id\030\001 \001(\t\022\013\n\003kwg\030\002 \001(\002\"" +
      "\025\n\003Ack\022\016\n\006status\030\001 \001(\t2R\n\rEnergyService\022" +
      "A\n\021ReportConsumption\022\027.energy_service.Re" +
      "ading\032\023.energy_service.AckB\026\n\022gRPC.Energ" +
      "yServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_energy_service_Reading_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_energy_service_Reading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_energy_service_Reading_descriptor,
        new java.lang.String[] { "MeterId", "Kwg", });
    internal_static_energy_service_Ack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_energy_service_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_energy_service_Ack_descriptor,
        new java.lang.String[] { "Status", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
