// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: energyService.proto
// Protobuf Java Version: 4.31.1

package gRPC.EnergyService;

/**
 * Protobuf type {@code energy_service.Reading}
 */
@com.google.protobuf.Generated
public final class Reading extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:energy_service.Reading)
    ReadingOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Reading.class.getName());
  }
  // Use Reading.newBuilder() to construct.
  private Reading(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Reading() {
    meterId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gRPC.EnergyService.EnergyServiceOuterClass.internal_static_energy_service_Reading_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gRPC.EnergyService.EnergyServiceOuterClass.internal_static_energy_service_Reading_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gRPC.EnergyService.Reading.class, gRPC.EnergyService.Reading.Builder.class);
  }

  public static final int METER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object meterId_ = "";
  /**
   * <code>string meter_id = 1;</code>
   * @return The meterId.
   */
  @java.lang.Override
  public java.lang.String getMeterId() {
    java.lang.Object ref = meterId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      meterId_ = s;
      return s;
    }
  }
  /**
   * <code>string meter_id = 1;</code>
   * @return The bytes for meterId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMeterIdBytes() {
    java.lang.Object ref = meterId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      meterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KWG_FIELD_NUMBER = 2;
  private float kwg_ = 0F;
  /**
   * <code>float kwg = 2;</code>
   * @return The kwg.
   */
  @java.lang.Override
  public float getKwg() {
    return kwg_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(meterId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, meterId_);
    }
    if (java.lang.Float.floatToRawIntBits(kwg_) != 0) {
      output.writeFloat(2, kwg_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(meterId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, meterId_);
    }
    if (java.lang.Float.floatToRawIntBits(kwg_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, kwg_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gRPC.EnergyService.Reading)) {
      return super.equals(obj);
    }
    gRPC.EnergyService.Reading other = (gRPC.EnergyService.Reading) obj;

    if (!getMeterId()
        .equals(other.getMeterId())) return false;
    if (java.lang.Float.floatToIntBits(getKwg())
        != java.lang.Float.floatToIntBits(
            other.getKwg())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMeterId().hashCode();
    hash = (37 * hash) + KWG_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getKwg());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gRPC.EnergyService.Reading parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gRPC.EnergyService.Reading parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gRPC.EnergyService.Reading parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gRPC.EnergyService.Reading parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gRPC.EnergyService.Reading parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gRPC.EnergyService.Reading parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gRPC.EnergyService.Reading parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static gRPC.EnergyService.Reading parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static gRPC.EnergyService.Reading parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static gRPC.EnergyService.Reading parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gRPC.EnergyService.Reading parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static gRPC.EnergyService.Reading parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gRPC.EnergyService.Reading prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code energy_service.Reading}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:energy_service.Reading)
      gRPC.EnergyService.ReadingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gRPC.EnergyService.EnergyServiceOuterClass.internal_static_energy_service_Reading_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gRPC.EnergyService.EnergyServiceOuterClass.internal_static_energy_service_Reading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gRPC.EnergyService.Reading.class, gRPC.EnergyService.Reading.Builder.class);
    }

    // Construct using gRPC.EnergyService.Reading.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      meterId_ = "";
      kwg_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gRPC.EnergyService.EnergyServiceOuterClass.internal_static_energy_service_Reading_descriptor;
    }

    @java.lang.Override
    public gRPC.EnergyService.Reading getDefaultInstanceForType() {
      return gRPC.EnergyService.Reading.getDefaultInstance();
    }

    @java.lang.Override
    public gRPC.EnergyService.Reading build() {
      gRPC.EnergyService.Reading result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gRPC.EnergyService.Reading buildPartial() {
      gRPC.EnergyService.Reading result = new gRPC.EnergyService.Reading(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(gRPC.EnergyService.Reading result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.meterId_ = meterId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.kwg_ = kwg_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gRPC.EnergyService.Reading) {
        return mergeFrom((gRPC.EnergyService.Reading)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gRPC.EnergyService.Reading other) {
      if (other == gRPC.EnergyService.Reading.getDefaultInstance()) return this;
      if (!other.getMeterId().isEmpty()) {
        meterId_ = other.meterId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (java.lang.Float.floatToRawIntBits(other.getKwg()) != 0) {
        setKwg(other.getKwg());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              meterId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 21: {
              kwg_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object meterId_ = "";
    /**
     * <code>string meter_id = 1;</code>
     * @return The meterId.
     */
    public java.lang.String getMeterId() {
      java.lang.Object ref = meterId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        meterId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string meter_id = 1;</code>
     * @return The bytes for meterId.
     */
    public com.google.protobuf.ByteString
        getMeterIdBytes() {
      java.lang.Object ref = meterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        meterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string meter_id = 1;</code>
     * @param value The meterId to set.
     * @return This builder for chaining.
     */
    public Builder setMeterId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      meterId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string meter_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMeterId() {
      meterId_ = getDefaultInstance().getMeterId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string meter_id = 1;</code>
     * @param value The bytes for meterId to set.
     * @return This builder for chaining.
     */
    public Builder setMeterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      meterId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private float kwg_ ;
    /**
     * <code>float kwg = 2;</code>
     * @return The kwg.
     */
    @java.lang.Override
    public float getKwg() {
      return kwg_;
    }
    /**
     * <code>float kwg = 2;</code>
     * @param value The kwg to set.
     * @return This builder for chaining.
     */
    public Builder setKwg(float value) {

      kwg_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float kwg = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKwg() {
      bitField0_ = (bitField0_ & ~0x00000002);
      kwg_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:energy_service.Reading)
  }

  // @@protoc_insertion_point(class_scope:energy_service.Reading)
  private static final gRPC.EnergyService.Reading DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gRPC.EnergyService.Reading();
  }

  public static gRPC.EnergyService.Reading getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Reading>
      PARSER = new com.google.protobuf.AbstractParser<Reading>() {
    @java.lang.Override
    public Reading parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Reading> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Reading> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gRPC.EnergyService.Reading getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

