# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: IChecker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'IChecker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eIChecker.proto\x12\tI_checker\"\"\n\x0bTemperature\x12\x13\n\x0btemperature\x18\x01 \x01(\x03\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x16\n\x07\x41verage\x12\x0b\n\x03\x61vg\x18\x01 \x01(\x02\x32x\n\x08IChecker\x12\x37\n\x0bstream_temp\x12\x16.I_checker.Temperature\x1a\x0e.I_checker.Ack(\x01\x12\x33\n\x0bget_average\x12\x10.I_checker.Empty\x1a\x12.I_checker.Averageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IChecker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPERATURE']._serialized_start=29
  _globals['_TEMPERATURE']._serialized_end=63
  _globals['_ACK']._serialized_start=65
  _globals['_ACK']._serialized_end=86
  _globals['_EMPTY']._serialized_start=88
  _globals['_EMPTY']._serialized_end=95
  _globals['_AVERAGE']._serialized_start=97
  _globals['_AVERAGE']._serialized_end=119
  _globals['_ICHECKER']._serialized_start=121
  _globals['_ICHECKER']._serialized_end=241
# @@protoc_insertion_point(module_scope)
