# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import IChecker_pb2 as IChecker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in IChecker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ICheckerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.stream_temp = channel.stream_unary(
                '/I_checker.IChecker/stream_temp',
                request_serializer=IChecker__pb2.Temperature.SerializeToString,
                response_deserializer=IChecker__pb2.Ack.FromString,
                _registered_method=True)
        self.get_average = channel.unary_unary(
                '/I_checker.IChecker/get_average',
                request_serializer=IChecker__pb2.Empty.SerializeToString,
                response_deserializer=IChecker__pb2.Average.FromString,
                _registered_method=True)


class ICheckerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def stream_temp(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_average(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ICheckerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'stream_temp': grpc.stream_unary_rpc_method_handler(
                    servicer.stream_temp,
                    request_deserializer=IChecker__pb2.Temperature.FromString,
                    response_serializer=IChecker__pb2.Ack.SerializeToString,
            ),
            'get_average': grpc.unary_unary_rpc_method_handler(
                    servicer.get_average,
                    request_deserializer=IChecker__pb2.Empty.FromString,
                    response_serializer=IChecker__pb2.Average.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'I_checker.IChecker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('I_checker.IChecker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IChecker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def stream_temp(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/I_checker.IChecker/stream_temp',
            IChecker__pb2.Temperature.SerializeToString,
            IChecker__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_average(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/I_checker.IChecker/get_average',
            IChecker__pb2.Empty.SerializeToString,
            IChecker__pb2.Average.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
