// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: energyService.proto
// Protobuf Java Version: 4.31.1

package gRPC.EnergyService;

@com.google.protobuf.Generated
public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy_service.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
