// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: energyService.proto
// Protobuf Java Version: 4.31.1

package gRPC.EnergyService;

@com.google.protobuf.Generated
public interface ReadingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy_service.Reading)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meter_id = 1;</code>
   * @return The meterId.
   */
  java.lang.String getMeterId();
  /**
   * <code>string meter_id = 1;</code>
   * @return The bytes for meterId.
   */
  com.google.protobuf.ByteString
      getMeterIdBytes();

  /**
   * <code>float kwg = 2;</code>
   * @return The kwg.
   */
  float getKwg();
}
